version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: solana_analytics
      POSTGRES_USER: solana_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # TimescaleDB (for time-series data - optional upgrade)
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_DB: solana_analytics_ts
      POSTGRES_USER: solana_user
      POSTGRES_PASSWORD: spectrum_2025
    ports:
      - "5433:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
  timescale_data: