# RPC Client Configuration

# Endpoints configuration
endpoints = [
    { url = "https://api.mainnet-beta.solana.com", weight = 1, requests_per_second = 100 },
    { url = "https://solana-api.projectserum.com", weight = 1, requests_per_second = 100 },
    { url = "https://rpc.ankr.com/solana", weight = 1, requests_per_second = 100 }
]

# Connection pool settings
pool_size = 10
keep_alive = "30s"

# Retry settings
max_retries = 5
base_delay = "100ms"
max_delay = "10s"

# Rate limiting
requests_per_second = 100

# Cache settings
cache_ttl = "60s"

# Timeout settings
timeout = "30s" 